Kusitms-26th-Ohttention/pickRAP-BE

.github/workflows/github-actions.yml
Dockerfile
docker-compose.yml
src/test/resources/application.properties

:tada: init: github-actions

---

.github/workflows/CD.yml
.github/workflows/CI.yml
src/main/java/pickRAP/server/domain/Member.java

github-actions
- Resolved: #2 
github-actions CI/CD 파일 분리

:rocket: Deploy: github-actions

---

.github/workflows/CD.yml
.github/workflows/CI.yml
src/main/java/pickRAP/server/domain/Member.java

- Resolved: #2 
- github-actions CI/CD 분리

🚀 Deploy: github-actions

---

src/main/java/pickRAP/server/controller/AuthController.java

- Resolved: #15 
- 비밀번호 조건검사 수정

:bug: Fix: 비밀번호 조건검사 수정

---

Dockerfile
build.gradle
src/main/java/pickRAP/server/common/BaseExceptionStatus.java
src/main/java/pickRAP/server/config/querydsl/QueryDslConfig.java
src/main/java/pickRAP/server/config/swagger/SwaggerConfig.java
src/main/java/pickRAP/server/controller/CategoryController.java
src/main/java/pickRAP/server/controller/dto/category/CategoryRequest.java
src/main/java/pickRAP/server/controller/dto/category/CategoryResponse.java
src/main/java/pickRAP/server/domain/category/Category.java
src/main/java/pickRAP/server/domain/member/Member.java
src/main/java/pickRAP/server/repository/category/CategoryRepository.java
src/main/java/pickRAP/server/service/category/CategoryService.java
src/main/resources/application-prod.properties
src/main/resources/application.properties
src/test/resources/application.properties

Feat: 카테고리 등록
- Resolved: #47 
- 카테고리 생성 API
- 도커파일 수정
- 프로메테우스 dependency, properties 추가

:sparkles: Feat: 카테고리 등록

---

src/main/java/pickRAP/server/common/BaseExceptionStatus.java
src/main/java/pickRAP/server/controller/CategoryController.java
src/main/java/pickRAP/server/controller/ScrapController.java
src/main/java/pickRAP/server/controller/dto/category/CategoryScrapResponse.java
src/main/java/pickRAP/server/controller/dto/scrap/HashtagRequest.java
src/main/java/pickRAP/server/controller/dto/scrap/ScrapDeleteRequest.java
src/main/java/pickRAP/server/controller/dto/scrap/ScrapFilterCondition.java
src/main/java/pickRAP/server/controller/dto/scrap/ScrapFilterRequest.java
src/main/java/pickRAP/server/controller/dto/scrap/ScrapRequest.java
src/main/java/pickRAP/server/controller/dto/scrap/ScrapResponse.java
src/main/java/pickRAP/server/controller/dto/scrap/ScrapSelectRequest.java
src/main/java/pickRAP/server/controller/dto/scrap/ScrapUpdateRequest.java
src/main/java/pickRAP/server/domain/member/Member.java
src/main/java/pickRAP/server/domain/scrap/Hashtag.java
src/main/java/pickRAP/server/domain/scrap/Scrap.java
src/main/java/pickRAP/server/domain/scrap/ScrapHashtag.java
src/main/java/pickRAP/server/domain/scrap/ScrapType.java
src/main/java/pickRAP/server/repository/category/CategoryRepositoryImpl.java
src/main/java/pickRAP/server/repository/scrap/HashtagRepository.java
src/main/java/pickRAP/server/repository/scrap/ScrapHashtagRepository.java
src/main/java/pickRAP/server/repository/scrap/ScrapRepository.java
src/main/java/pickRAP/server/repository/scrap/ScrapRepositoryCustom.java
src/main/java/pickRAP/server/repository/scrap/ScrapRepositoryImpl.java
src/main/java/pickRAP/server/service/category/CategoryService.java
src/main/java/pickRAP/server/service/s3/S3Service.java
src/main/java/pickRAP/server/service/scrap/ScrapService.java
src/main/resources/application.properties
src/test/resources/application.properties

- 스크랩 저장, 수정, 삭제 api 구현
- 스크랩 검색, 필터링 페이징 api 구현
- 카테고리 조회 api 수정

:sparkles: Feat: 스크랩 api

---

src/main/java/pickRAP/server/controller/CategoryController.java
src/main/java/pickRAP/server/controller/ScrapController.java
src/main/java/pickRAP/server/service/scrap/ScrapService.java

:art: Form: 경로 수정

---

src/main/java/pickRAP/server/controller/ScrapController.java
src/main/java/pickRAP/server/controller/dto/scrap/ScrapRequest.java
src/main/java/pickRAP/server/controller/dto/scrap/ScrapUpdateRequest.java
src/main/java/pickRAP/server/service/scrap/ScrapService.java

Form: 스크랩 요청 DTO 구조 변경
- 스크랩 저장, 수정 request dto 수정

:art: Form: 스크랩 요청 DTO 구조 변경

---

src/main/java/pickRAP/server/service/auth/AuthService.java
src/main/java/pickRAP/server/service/auth/DefaultImageEnv.java
src/main/java/pickRAP/server/service/oauth/KakaoEnv.java
src/main/java/pickRAP/server/service/oauth/NaverEnv.java

:bug: Fix : 기본 프로필 이미지 URL 수정

---

src/main/java/pickRAP/server/common/BaseExceptionStatus.java
src/main/java/pickRAP/server/controller/CategoryController.java
src/main/java/pickRAP/server/controller/ScrapController.java
src/main/java/pickRAP/server/controller/dto/scrap/ScrapPageResponse.java
src/main/java/pickRAP/server/controller/dto/scrap/ScrapRequest.java
src/main/java/pickRAP/server/service/category/CategoryService.java
src/main/java/pickRAP/server/service/scrap/ScrapService.java

- 스크랩 request 구조 변경
- 스크랩 response 구조 변경

Form: 스크랩 dto 구조 변경

---

src/main/java/pickRAP/server/common/BaseExceptionStatus.java
src/main/java/pickRAP/server/controller/CategoryController.java
src/main/java/pickRAP/server/controller/ScrapController.java

- Resolved: #이슈번호
- 스크랩 response 구조 변경

🎨 Form: 스크랩 response 구조 변경

---

src/main/java/pickRAP/server/controller/dto/scrap/ScrapResponse.java
src/main/java/pickRAP/server/service/category/CategoryService.java
src/main/java/pickRAP/server/service/scrap/ScrapService.java

Improve: URL 미리보기 추가
- URL 미리보기 추가

:zap: Improve: URL 미리보기 추가

---

src/main/java/pickRAP/server/controller/dto/scrap/ScrapResponse.java
src/main/java/pickRAP/server/repository/scrap/ScrapRepositoryImpl.java
src/main/java/pickRAP/server/service/scrap/ScrapService.java

Form: 스크랩 response 구조 변경
- 스크랩 response 구조 변경

:art: Form: 스크랩 response 구조 변경

---

src/main/java/pickRAP/server/controller/MagazineController.java
src/main/java/pickRAP/server/controller/dto/magazine/MagazineListResponse.java
src/main/java/pickRAP/server/service/magazine/MagazineService.java

- Resolved: #86
- 스웨거 출력 오류(반환타입) 수정

🐛 Fix: 매거진 API 반환 타입 수정

---

src/main/java/pickRAP/server/controller/dto/magazine/MagazinePageResponse.java
src/main/java/pickRAP/server/controller/dto/magazine/MagazineResponse.java

🚚 Rename: 변수명 카멜케이스

---

src/main/java/pickRAP/server/controller/CategoryController.java
src/main/java/pickRAP/server/controller/dto/category/CategoryContentsResponse.java
src/main/java/pickRAP/server/service/magazine/MagazineService.java

- Resolved: #98
- 카테고리 콘텐츠 불러오기 API json 파라미터 오류 수정
- 매거진 API 내에 예외 처리

매거진 API 수정

---

src/main/java/pickRAP/server/controller/MagazineController.java
src/main/java/pickRAP/server/service/magazine/MagazineService.java

- Resolved: #98 
- 매거진 제목 중복을 체크하는 API를 분리했습니다.

♻️ Refactor: 제목 중복 여부 확인 API 분리

---

src/main/java/pickRAP/server/common/BaseExceptionStatus.java
src/main/java/pickRAP/server/controller/MagazineController.java
src/main/java/pickRAP/server/service/magazine/MagazineService.java

- Resolved: #98 
- 매거진 수정 API에 작성된 예외 throw에 오타를 수정했습니다.

🐛 Fix: Magazine 수정 예외 오류 수정

---

src/main/java/pickRAP/server/controller/dto/category/CategoryScrapResponse.java
src/main/java/pickRAP/server/service/category/CategoryService.java

- Resolved: #95 
- 카테고리 & 스크랩 response 수정

:bug: Fix: 카테고리 & 스크랩 response 수정

---

src/main/java/pickRAP/server/controller/AuthController.java
src/main/java/pickRAP/server/service/auth/AuthService.java

domain 속성을 하나 빼먹어서 강제 머지할게요....ㅎㅎ

:bug: Fix: 쿠키 domain 추가

---

src/main/java/pickRAP/server/config/security/jwt/TokenProvider.java
src/main/java/pickRAP/server/controller/dto/auth/MemberSignInRequest.java
src/main/java/pickRAP/server/controller/dto/auth/MemberSignUpRequest.java
src/main/java/pickRAP/server/controller/dto/oauth/NaverProfile.java
src/test/java/pickRAP/server/auth/AuthEnv.java
src/test/java/pickRAP/server/auth/AuthServiceTest.java
src/test/java/pickRAP/server/auth/JwtTest.java
src/test/resources/application.properties

- Resolved: #114 
- AuthService 관련 테스트
- 쿠키 발급 + 토큰 관련 controller 테스트

:white_check_mark: Test: 사용자 인증 테스트

---

src/main/java/pickRAP/server/controller/dto/magazine/MagazinePageRequest.java
src/main/java/pickRAP/server/controller/dto/magazine/MagazineRequest.java
src/main/java/pickRAP/server/domain/member/Member.java
src/main/java/pickRAP/server/service/magazine/MagazineService.java
src/test/java/pickRAP/server/magazine/MagazineServiceTest.java

- Resolved: #113 
매거진 기능에 대한 서비스 단위 테스트 코드를 작성합니다.
- 매거진 생성 / 조회 테스트
- 매거진 수정 테스트
- 매거진 삭제 테스트
- 매거진 예외처리 테스트

✅ Test : 매거진 테스트 코드

---

src/main/java/pickRAP/server/repository/magazine/MagazinePageRepository.java
src/main/java/pickRAP/server/service/scrap/ScrapService.java

Fix: 외래키 무결성 위반 수정
- Resolved: #이슈번호
-
|스크린샷|
|:--:|
|파일첨부바람|

:bug: Fix: 외래키 무결성 위반 수정

---

src/main/java/pickRAP/server/common/BaseExceptionStatus.java
src/main/java/pickRAP/server/controller/ProfileController.java
src/main/java/pickRAP/server/controller/ScrapController.java
src/main/java/pickRAP/server/service/scrap/ScrapService.java
src/main/java/pickRAP/server/util/s3/S3Util.java

- Resolved: #이슈번호
-
|스크린샷|
|:--:|
|파일첨부바람|

Refactor: 파일 업로드 예외처리 추가

---

.github/workflows/CD.yml
appspec.yml
docker-compose.yml
nginx/default.conf
scripts/execute.sh
scripts/switch-container.sh

- Resolved: #144 144
- AWS S3, Code Deploy, Nginx, docker를 활용하여 무중단 배포를 구현했습니다. 
- 자세한 아키텍처는 아래 스크린샷 첨부합니다. 
- CD.yml 내용 수정
|스크린샷|
|:--:|
|![image](https://user-images.githubusercontent.com/78305431/215158374-3034ee22-12d1-4699-ad10-0f109faee2a3.png)|
- https://yongc.tistory.com/28
- https://wbluke.tistory.com/40

🚀 무중단 배포 적용

---

Dockerfile

Fix: heap 메모리 크기 수정
- Resolved: #155 
- jvm heap 메모리 크기 수정

:bug: Fix: heap 메모리 크기 수정

---

src/main/java/pickRAP/server/ServerApplication.java
src/test/java/pickRAP/server/hashtag/HashtagServiceTest.java

- 해시태그 분석 관련 서비스 테스트
- 브랜치가 나눠져 있어서 우선, 해시태그 분석 테스트 코드 먼저 올립니다.

Test: 해시태그 분석 테스트
